version: '3.8'
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  queue:
    container_name: Queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ideeo
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  db:
    driver: local
networks:
  laravel-exa:
    driver: bridge