version: '3.8'
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c 'php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0'
    command: >
      sh -c "php artisan migrate && php artisan passport:install && php artisan db:seed && php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
    networks:
      - laravel
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ideeo'
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - laravel
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql_db:
    driver: local
networks:
  laravel:
    driver: bridge